export default () => ({
  TYPE_INPUT: 'TYPE_INPUT',
  TYPE_NUMBERINPUT: 'TYPE_NUMBERINPUT',
  TYPE_TEXTAREA: 'TYPE_TEXTAREA',
  TYPE_CHECKBOXGROUP: 'TYPE_CHECKBOXGROUP',
  TYPE_RADIOGROUP: 'TYPE_RADIOGROUP',
  TYPE_DROPDOWN: 'TYPE_DROPDOWN',
  TYPE_CUSTOM: 'TYPE_CUSTOM'
});